import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import Navbar from "../components/navbar/Navbar";
import getCurrentUser from "@/components/actions/getCurrentUser";
import RegisterModal from "@/components/modal/RegisterModal";
import LoginModal from "@/components/modal/LoginModal";
import RentModal from "@/components/modal/RentModal";
import ToasterProvider from "@/providers/ToasterProvider";
import getAdmin from "@/components/actions/getAdmin";
import SearchModal from "@/components/modal/SearchModal";
import HeroModal from "@/components/modal/HeroModal";
import ReservationModal from "@/components/modal/ReservationModal";
import getListingAdmin from "@/components/actions/getlListingsAdmin";
import getNotifications from "@/components/actions/getNotifications";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  const admin = await getAdmin();
  const listings = await getListingAdmin({ adminId: admin?.id });
  const notifi = await getNotifications();
  return (
    <html lang="en">
      <link
        rel="icon"
        type="image/svg+xml"
        href="/logo.svg"
      />
      <body className={inter.className}>
        <SearchModal />
        <RegisterModal />
        <LoginModal />
        <RentModal />
        <HeroModal />
        <Navbar
          currentUser={currentUser}
          admin={admin}
          notifi={notifi}
        />
        <ReservationModal listings={listings} />
        <ToasterProvider />
        <div className="py-[100px]">{children}</div>
      </body>
    </html>
  );
}
